jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SetUp Java (Zulu 8)
        uses: actions/setup-java@v3      
        with:
          distribution: 'zulu'
          java-version: '8'
          architecture: x86      
      - name: Build with Ant
        run: ant  -Dnb.internal.action.name=rebuild clean jar
